server:
  port: 8888

jasypt:
  password: ${JASYPT_PASSWORD}

aes256:
  key: ${AES_KEY}

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/lsnwan/springboot-react-ts-blog/tree/main/config/files


