spring:

  datasource:
    url: jdbc:mariadb://localhost:3306/blog
    username: blog
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(BXsWBaf3j3Mt8TS7+3N9wxSqxsaqhLZwej6bsMxpVxc=)
    password: ENC(hJIVz1MlhD5F5KKb0SoyXnZLTTH/KbaUXWYYbh7SZA4=)
    properties:
      mail.smtp.auth: true
      mail.smtp.timeout: 5000
      mail.smtp.starttls.enable: true


logging:
  level:
    com.example.backend: DEBUG

jwt:
  header: Authorization
  secret: Y3FpYWVydWhvZ2NxbnVlaGdvcWl1ZWNoZ29pcXVnb2lxcmVidmlxcmhub2NlcnV5Z2hub2NxdWVyaGdvcW5peWVtZ3JxaXVocmJvdXFuY29p
  expired-time-token: 31557600000

jasypt:
  password: 1234567890123456

aes256:
  key: 1234567890123456

app:
  host: http://localhost:8080

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000

kakao:
  client:
    id: ENC(eDw+ByiufxmCmOqEkd3zavD/wt7bdSczJ10W2/XmPTkOVGq38hL77rEJcTSpewEZ)
    secret: ENC(/fEVJ/hyuIjHXud3U0RVSlUyfUoEKr85ik/Xq9DD0iHXr1D1ysioHz8wZzlutN2o)