spring:

  datasource:
    url: jdbc:mariadb://localhost:3306/blog
    username: blog
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    com.example.backend: DEBUG

jwt:
  header: Authorization
  secret: Y3FpYWVydWhvZ2NxbnVlaGdvcWl1ZWNoZ29pcXVnb2lxcmVidmlxcmhub2NlcnV5Z2hub2NxdWVyaGdvcW5peWVtZ3JxaXVocmJvdXFuY29p
  expired-time:
    access-token: 86400000
    refresh-token: 31557600000

jasypt:
  password: 1234567890123456

aes256:
  key: 1234567890123456