spring:

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/blog
    username: blog
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    com.example.backend: DEBUG
    org.hibernate:
      type:
        descriptor.sql: trace

jwt:
  header: Authorization
  secret: Y3FpYWVydWhvZ2NxbnVlaGdvcWl1ZWNoZ29pcXVnb2lxcmVidmlxcmhub2NlcnV5Z2hub2NxdWVyaGdvcW5peWVtZ3JxaXVocmJvdXFuY29p
  expired-time-token: 31557600000

jasypt:
  password: ${JASYPT_PASSWORD}

aes256:
  key: 1234567890123456

app:
  host: http://localhost:8080
  files: D:/web/blog/files/

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000

mybatis:
  mapper-locations: mappers/*.xml
